### ISSUE TITLE
One question about the formulas in the paper

### ISSUE THREAD

**Issue by qaz88666** [wz7in/CVPR2023-VLSAT#10]
Thanks for your contribution, In your paper equation 1 represents the initialization of the edge features, at this time bi does not take the log operation, but in the code, it shows the log operation

![微信图片_20230902182530](https://github.com/wz7in/CVPR2023-VLSAT/assets/143877344/740d2ecb-696b-4c00-be51-c6617ac4419d)
![d077763a3d1d07d6763932477cd836e](https://github.com/wz7in/CVPR2023-VLSAT/assets/143877344/6868f1bf-4171-4297-b080-28fa02cb4118)

**Comment by wtt0213** [comment]
We update the code after paper release. You can just follow the code~
