### ISSUE TITLE
Question about util_label and util_search in utils

### ISSUE THREAD

**Issue by zhenwangrs** [wz7in/CVPR2023-VLSAT#11]
Hello, in the gen_data_pt.py and gen_data.py, you use util_label and util_search in utils, however, I am not able to find those two python file in the utils folder. Since those two .py is very important in generating data, where I can find them. Looking forward to your reply!

**Comment by wtt0213** [comment]
You can find these file in the origin paper 3DSSG(https://github.com/ShunChengWu/3DSSG)

**Comment by zhenwangrs** [comment]
Thanks for your reply, this really help me a lot.
