### ISSUE TITLE
src.lib

### ISSUE THREAD

**Issue by liyifan-123** [wz7in/CVPR2023-VLSAT#2]
Excuse me, I can not find src.lib under the src floder, could you please help me to solve this problem?

`Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from src.model.model import MMGNet
  File "/data/lyf/3DSSG_code/CVPR2023-VLSAT-main/src/model/model.py", line 13, in <module>
    from src.model.SGFN_MMG.model import Mmgnet
  File "/data/lyf/3DSSG_code/CVPR2023-VLSAT-main/src/model/SGFN_MMG/model.py", line 11, in <module>
    from src.model.model_utils.network_PointNet import (PointNetfeat,
  File "/data/lyf/3DSSG_code/CVPR2023-VLSAT-main/src/model/model_utils/network_PointNet.py", line 11, in <module>
    from src.lib.pointnet.graph import GraphTripleConvNet
ModuleNotFoundError: No module named 'src.lib'`

**Comment by wz7in** [comment]
Yeah, you can get the related files in [3DSSG](https://github.com/ShunChengWu/3DSSG/tree/master/src/pointnet) if you want to use pointnet as our paper's claim, I forgot to include it in this codebase. Still, as in our experiment, the performance of the instance-level feature encoder in this codebase is similar to pointnet.

**Comment by zzhmx** [comment]
But the 3DSSG/lib has gone.

**Comment by mfp0610** [comment]
https://github.com/ShunChengWu/3DSSG/tree/2414f37750f858732e16a46a93b36c524aba6d79/old/src
You can refer to this old version of 3DSSG
