### ISSUE TITLE
get_zero_shot_recall

### ISSUE THREAD

**Issue by liyifan-123** [wz7in/CVPR2023-VLSAT#4]
`File "/data/lyf/3DSSG_code/CVPR2023-VLSAT-main/src/model/model.py", line 255, in validation
    zero_shot_recall, non_zero_shot_recall, all_zero_shot_recall = get_zero_shot_recall(topk_triplet_list, cls_matrix_list, self.dataset_valid.classNames, self.dataset_valid.relationNames)`

there is not function name get_zero_shot_recall. could you please tell me how to fix it ? I have try `from data.get_zero_shot_val import get_zero_shot_recall` but the error is `ValueError: too many values to unpack (expected 3)`

**Comment by wz7in** [comment]
https://github.com/wz7in/CVPR2023-VLSAT/blob/b0ac0036b723a1c0b2457a3481a1f9aac855033f/src/utils/eva_utils_acc.py#L267
