### ISSUE TITLE
about config_example.json

### ISSUE THREAD

**Issue by yang1332133** [wz7in/CVPR2023-VLSAT#5]
Excuse me, I can not find the config_example.json in your project, could you please send me this file ? thanks! my email is 2087191953@qq.com

**Comment by wz7in** [comment]
has sent to your email

**Comment by clgx00** [comment]
@wz7in Hi! I also noticed that there is a config file mentioned in the project, specifically the config_example.json. However, I couldn't find the actual file in the repository. Could you also send me this file？Thank you very much for your time and consideration.

My email is 496659299@qq.com

**Comment by liuyuex97** [comment]
Hi would the config file be potentially released in the future?

**Comment by zzhmx** [comment]
Excuse me, I can not find the config_example.json in your project, could you please send me this file ? thanks! my email is [3200133672@qq.com]
