### ISSUE TITLE
请问一下有提供该模型的预训练权重文件吗？

### ISSUE THREAD

**Issue by zhiwei-Wang-light** [wz7in/CVPR2023-VLSAT#6]
我想运行python -m main --mode eval --config <config_path> --exp <exp_name>，请问一下我是否需要自己训练之后才能验证？关于<config_path> 我应该指向mmgnet.json ，然后<exp_name>指向"Mmgnet"吗？我在运行的时候还会出现ModuleNotFoundError: No module named 'src.lib'的问题，这个问题怎么解决？谢谢

**Comment by zzhmx** [comment]
> 我想运行python -m main --mode eval --config <config_path> --exp <exp_name>，请问一下我是否需要自己训练之后才能验证？关于<config_path> 我应该指向mmgnet.json ，然后<exp_name>指向"Mmgnet"吗？我在运行的时候还会出现ModuleNotFoundError: No module named 'src.lib'的问题，这个问题怎么解决？谢谢

请问解决了吗
